FROM python:3.12-slim

WORKDIR /opt/app

COPY requirements.txt requirements.txt
COPY .env .env

RUN  pip install --no-cache-dir --upgrade pip \
     && pip install -r requirements.txt

COPY ./etl .


CMD [ "python", "main.py" ]


